import backpackImg from "@assets/generated_images/modern_minimal_backpack_product_shot.png";
import textbookImg from "@assets/generated_images/engineering_textbook_on_desk.png";
import jacketImg from "@assets/generated_images/vintage_denim_jacket_on_hanger.png";
import tennisImg from "@assets/generated_images/tennis_racket_and_balls_on_court.png";
import bioBookImg from "@assets/generated_images/biology_textbook_on_wooden_library_table.png";
import csBookImg from "@assets/generated_images/computer_science_algorithms_textbook.png";
import laptopImg from "@assets/generated_images/gaming_laptop_with_rgb_keyboard.png";
import watchImg from "@assets/generated_images/smartwatch_on_wrist.png";
import hoodieImg from "@assets/generated_images/grey_university_hoodie.png";
import sneakersImg from "@assets/generated_images/vintage_sneakers.png";
import lampImg from "@assets/generated_images/modern_desk_lamp.png";
import beanbagImg from "@assets/generated_images/comfortable_bean_bag_chair.png";
import basketballImg from "@assets/generated_images/basketball_on_court.png";
import yogaImg from "@assets/generated_images/yoga_mat_and_water_bottle.png";

export const CATEGORIES = [
  { id: "all", name: "All Items" },
  { id: "textbooks", name: "Textbooks" },
  { id: "electronics", name: "Electronics" },
  { id: "clothing", name: "Clothing" },
  { id: "furniture", name: "Furniture" },
  { id: "sports", name: "Sports & Gear" },
];

export const PRODUCTS = [
  {
    id: 1,
    title: "Calculus: Early Transcendentals 8th Ed",
    price: 45,
    category: "textbooks",
    image: textbookImg,
    location: "Student Union",
    seller: "Sarah M.",
    condition: "Good",
    description: "Used for one semester. No highlighting inside. Covers match. Can meet on main campus.",
    posted: "2 hours ago",
  },
  {
    id: 7,
    title: "Wilson Tennis Racket + Balls",
    price: 85,
    category: "sports",
    image: tennisImg,
    location: "Rec Center",
    seller: "David L.",
    condition: "Like New",
    description: "Wilson Clash 100. Used only twice. Comes with a fresh can of balls. Grip size 4 3/8.",
    posted: "Just now",
  },
  {
    id: 8,
    title: "Biology: Campbell 11th Edition",
    price: 65,
    category: "textbooks",
    image: bioBookImg,
    location: "Science Library",
    seller: "Emma R.",
    condition: "Fair",
    description: "Some wear on cover but pages are clean. Essential for BIO 101.",
    posted: "1 hour ago",
  },
  {
    id: 9,
    title: "Introduction to Algorithms (CLRS)",
    price: 55,
    category: "textbooks",
    image: csBookImg,
    location: "Engineering Hall",
    seller: "James C.",
    condition: "Like New",
    description: "The bible of algorithms. Barely opened. Dropped the class.",
    posted: "3 hours ago",
  },
  {
    id: 10,
    title: "Alienware M15 Gaming Laptop",
    price: 850,
    category: "electronics",
    image: laptopImg,
    location: "North Dorms",
    seller: "Marcus T.",
    condition: "Good",
    description: "RTX 3060, 16GB RAM. Runs everything max settings. Upgrading to desktop.",
    posted: "5 hours ago",
  },
  {
    id: 11,
    title: "Galaxy Watch 4 Classic",
    price: 120,
    category: "electronics",
    image: watchImg,
    location: "Student Gym",
    seller: "Lisa P.",
    condition: "Like New",
    description: "Black 46mm. Comes with charger and extra band. Battery lasts 2 days.",
    posted: "6 hours ago",
  },
  {
    id: 12,
    title: "Grey University Hoodie (M)",
    price: 25,
    category: "clothing",
    image: hoodieImg,
    location: "Bookstore",
    seller: "Tom H.",
    condition: "Good",
    description: "Official uni merch. Super soft inside. Size Medium but fits large.",
    posted: "1 day ago",
  },
  {
    id: 13,
    title: "Vintage Nike Air Max 90s",
    price: 45,
    category: "clothing",
    image: sneakersImg,
    location: "Art Building",
    seller: "Sophie L.",
    condition: "Vintage",
    description: "Size 10. Classic colorway. Soles still have plenty of life.",
    posted: "2 days ago",
  },
  {
    id: 14,
    title: "Modern LED Desk Lamp",
    price: 20,
    category: "furniture",
    image: lampImg,
    location: "West Towers",
    seller: "Kevin N.",
    condition: "Like New",
    description: "Adjustable brightness and color temp. USB charging port in base.",
    posted: "3 days ago",
  },
  {
    id: 15,
    title: "Comfy Grey Bean Bag",
    price: 30,
    category: "furniture",
    image: beanbagImg,
    location: "South Commons",
    seller: "Rachel G.",
    condition: "Good",
    description: "Perfect for dorm gaming or reading. Cover is washable.",
    posted: "4 days ago",
  },
  {
    id: 16,
    title: "Spalding Indoor/Outdoor Basketball",
    price: 15,
    category: "sports",
    image: basketballImg,
    location: "Rec Center",
    seller: "Mike J.",
    condition: "Good",
    description: "Standard size 7. Good grip. Used for one intramural season.",
    posted: "5 days ago",
  },
  {
    id: 17,
    title: "Yoga Mat + Water Bottle Set",
    price: 25,
    category: "sports",
    image: yogaImg,
    location: "Wellness Center",
    seller: "Anna K.",
    condition: "New",
    description: "Brand new, never used. Thick foam mat and insulated bottle.",
    posted: "1 week ago",
  },
  {
    id: 2,
    title: "Herschel Little America Backpack",
    price: 60,
    category: "clothing",
    image: backpackImg,
    location: "North Dorms",
    seller: "Alex K.",
    condition: "Like New",
    description: "Barely used grey backpack. Laptop sleeve fits 15 inch macbook. Waterproof.",
    posted: "5 hours ago",
  },
  {
    id: 3,
    title: "Vintage Denim Jacket (L)",
    price: 35,
    category: "clothing",
    image: jacketImg,
    location: "Library Plaza",
    seller: "Jordan T.",
    condition: "Vintage",
    description: "Authentic 90s denim jacket. Oversized fit. Perfect condition, no stains.",
    posted: "1 day ago",
  },
  {
    id: 4,
    title: "Sony WH-1000XM4 Headphones",
    price: 180,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=1000",
    location: "Engineering Hall",
    seller: "Mike R.",
    condition: "Good",
    description: "Noise cancelling works perfectly. Comes with case and charging cable. Slight wear on ear pads.",
    posted: "2 days ago",
  },
  {
    id: 5,
    title: "Mini Fridge (Black)",
    price: 50,
    category: "furniture",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&q=80&w=1000",
    location: "West Towers",
    seller: "Emily W.",
    condition: "Fair",
    description: "Keeps things cold. Freezer compartment works well. Sticker residue on side but easy to clean.",
    posted: "3 days ago",
  },
  {
    id: 6,
    title: "iPad Air 4th Gen + Pencil",
    price: 400,
    category: "electronics",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=1000",
    location: "Design Center",
    seller: "Chris P.",
    condition: "Like New",
    description: "Blue sky color. 64GB. Screen protector installed since day 1. Includes Apple Pencil 2.",
    posted: "4 hours ago",
  },
];

export const MESSAGES = [
  {
    id: 1,
    user: "Sarah M.",
    lastMessage: "Is the textbook still available?",
    time: "10:30 AM",
    unread: true,
    avatar: "SM",
  },
  {
    id: 2,
    user: "Alex K.",
    lastMessage: "Thanks! See you at the union.",
    time: "Yesterday",
    unread: false,
    avatar: "AK",
  },
];